name: logify
description: "Attendance + Task Tracking App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Animation
  lottie: ^3.3.2
  animated_splash_screen: ^1.3.0
  font_awesome_flutter: ^10.12.0
  slide_to_act: ^2.0.2
  google_fonts: ^6.1.0
  intl: ^0.20.2

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.0
  firebase_app_check: ^0.3.2+10

  # Sign In (optional)
  google_sign_in: ^6.2.1

  # Storage & Local
  shared_preferences: ^2.2.2
  connectivity_plus: ^7.0.0

  # Location & Maps
  location: ^8.0.1
  geocoding: ^4.0.0
  geolocator: ^9.0.2

  # IMAGE PICKER
  image_picker: ^1.2.1

  # DATE PICKER UI
  month_year_picker: ^0.5.0+1

  # HTTP FOR CLOUDINARY
  http: ^1.2.2

  # State Management
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg.png
    - assets/images/default_user.png
    - assets/animations/animation_intro.json
    - assets/animations/animation_task.json
    - assets/icon/logo.png
    - assets/icon/icon.png

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Aariel
      fonts:
        - asset: assets/fonts/Aariel.otf
    - family: AarielBold
      fonts:
        - asset: assets/fonts/Aariel-Bold.otf
          weight: 700
    - family: Bileha
      fonts:
        - asset: assets/fonts/Bileha.otf
    - family: Bonsad
      fonts:
        - asset: assets/fonts/Bonsad-Regular.otf
    - family: Gendy
      fonts:
        - asset: assets/fonts/Gendy.otf
    - family: Rogbold
      fonts:
        - asset: assets/fonts/Rogbold.otf
          weight: 700
    - family: Serif
      fonts:
        - asset: assets/fonts/serif.ttf