name: image_magic
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.2.1
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  gal: ^2.3.2
  google_fonts: ^6.3.3
  flutter_riverpod: ^2.6.1
  dotted_border: ^3.1.0
  phosphor_flutter: ^2.1.0
  image: ^4.5.4
  file_picker: ^8.1.4 # Upgraded for Android v2 embedding support

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
